In [1]:
import numpy as np

In [2]:
my_list = [i for i in range(10)]
print(my_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [3]:
my_list * 2 #this will just duplicate the list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
my_arr = np.array(my_list)
type(my_arr)

numpy.ndarray

In [5]:
my_arr * 2   # this will multiply all the numbers inside.

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
my_arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [12]:
        # np.array([[r1], [r2], [r3]])
        
my_arr = np.array([[1,2,3], [4, 5, 6], [7,8,9]])
type(my_arr)
# my_arr + 2  # adds2 to each element


array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [13]:
#getting the row


my_arr[:, 0:1]          # esari [r, c] select garne milxa    # row bhaneko 0:3 ho which excludes 3.
                        # so row bhaneko [:] esari line ho

array([[1],
       [4],
       [7]])

In [16]:
my_arr[0:2, :]         #row ma value halyo bhane row aaunxa. column full linxa esle chai

array([[1, 2, 3],
       [4, 5, 6]])

* # arange



In [18]:
my_arr = np.arange(10)   #return evenly spaced values within a given interval.
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
my_arr = np.arange(0,10, 2)  # step +2 xa so interval 2 hunxa.
my_arr

array([0, 2, 4, 6, 8])

* # zeros and ones



In [21]:
Z = np.zeros(3)   # yo le chai 0 values haldinxa. sometime for balancing the data set.   #1 D array dinxa.
Z

array([0., 0., 0.])

In [23]:
new_z = np.zeros((3,3))   # Tuple rakhnu parxa esma chai. 2D array dinxa esle. 3, 3 matrix dinxa else 0 value ko . 
new_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
o_arr = np.ones(3)    #1 return garxa 1d array ko
o_arr

array([1., 1., 1.])

In [26]:
n_o_arr = np.ones((6,6))
n_o_arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

* # linspace 
Return evenly spaced numbers over a specified interval. 

In [30]:
L = np.linspace(0,25, 2)    #last ko 2 ..this gives 2 values evenly distributed among the 0 and 25 range. 
L

array([ 0., 25.])

In [36]:
evenly_spaced_array = np.linspace(0,25, 9)      #esma chai range exclude gardaina.
evenly_spaced_array

array([ 0.   ,  3.125,  6.25 ,  9.375, 12.5  , 15.625, 18.75 , 21.875,
       25.   ])

* # reshape 
esle chai rebuild in the 2d array.

In [37]:
evenly_spaced_2darray = evenly_spaced_array.reshape(3,3)
evenly_spaced_2darray

array([[ 0.   ,  3.125,  6.25 ],
       [ 9.375, 12.5  , 15.625],
       [18.75 , 21.875, 25.   ]])

* # eye 
creates an identity matrix

In [39]:
I2 = np.eye(2)  #creates 2 row 2 colum of 1,0 and 0, 1
I2

array([[1., 0.],
       [0., 1.]])

In [41]:
I4 = np.eye(4)    # creates 4 row column of 1, 0, 0, 0 and esari nai move hudai janxa
I4 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [42]:
I43 = np.eye(4,3)      #makes the array into 4 by 3 matrix 
I43

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [44]:
I43[0:2, 0:2]   #slicing the arr

array([[1., 0.],
       [0., 1.]])

* # Random 
numpy also has lots of ways to create rando num arrays:

* # rand
create an array of given shape and populate it with random samples form a uniform disribution over[0, 1]

In [46]:
import random

In [48]:
arr = np.random.rand(3,4)   #creates a 2 list by including random values in the list
arr

array([[0.57045059, 0.59996172, 0.42565576, 0.64932871],
       [0.19753164, 0.22681259, 0.82288332, 0.95368035],
       [0.13135967, 0.19513354, 0.36720871, 0.47380043]])

In [49]:
from numpy.random import rand

In [52]:
arr_simple = rand(3,4) 
arr_simple

array([[0.55910071, 0.63583309, 0.44047706, 0.88573977],
       [0.24056865, 0.87400369, 0.45202842, 0.35512586],
       [0.37278527, 0.65815333, 0.59969353, 0.73356569]])

* # randn
return a sample (or samples from the "standard normal" distribution. Unlike rand which is uniform:

In [53]:
from numpy.random import randn

In [54]:
mat = randn(3,2)
mat

array([[ 0.43327422,  0.47479725],
       [ 0.34679995, -0.3138673 ],
       [ 0.28404724,  0.62931214]])

In [55]:
mat1 = randn(3)
mat1

array([-0.11208818, -0.2447477 ,  0.11777371])

In [66]:
seq = [i for i in range(5)]
l = list(filter(lambda x: x == x ** 2, seq))    #returns the value which satisfies 
l

[0, 1]

In [64]:
l = lambda x: x.split("@")[0]
l("mdoumbia@howard.edu")

'mdoumbia'